### ISSUE TITLE
It is not eliminating nor generating the reports

### ISSUE THREAD

**Issue by martins07** [Conexiam/alfresco-expirable-content#2] opened 2017-03-15 14:06 UTC
Hi jeff, put the expiration date on the document and your rule to delete it when it expires, BUT neither when it is the day nor after the day of expiration it deletes it, it is still in the same folder and nothing appears in the Expirable folder Content Reports.
Note: I use Alfresco 5.1.g 201606.
Thank you very much for your help.

**Comment by jpotts** [comment] 2017-03-16 18:54
Just FYI, I don't think this is the cause of your problem, but you should know that 201606 is an EA release, not a stable GA release.

**Comment by jpotts** [comment] 2017-03-16 19:06
To test that your document has the proper value, go to the Node Browser and do an Alfresco FTS search using the following query:
cxme:expirationDate:[MIN to NOW]

If you are getting results back that means you have documents with the proper property set, but the scheduled action has not yet run. If that is the case, check your alfresco-global.properties file and validate that your cron expression is set properly:

    com.conexiam.expirable.jobs.deleteExpiredContent.cronexpression=0 0/5 * * * ?
    com.conexiam.expirable.jobs.deleteExpiredContent.cronstartdelay=240000

The first property says that the action will run every 5 minutes. The second says that the job will not run within 4 minutes of starting the server.

Please validate these things and let me know if you still see a problem.

**Comment by jpotts** [comment] 2017-03-16 19:22
Could not reproduce this in 201604-GA, 201605-GA, or 201612-GA. Closing as not a bug. Feel free to re-open with more specifics if you continue to have problems.

**Closed as completed by jpotts** 2017-03-16 19:22 UTC
